import { Invoice } from "../types/invoice";
import { KardexEntry, Product } from "../types/product";
import { Quote } from "../types/quote";
import { Sale } from "../types/sale";

export const mockProducts: Product[] = [
  {
    id: "1",
    sku: "TECH-001",
    name: "Laptop Dell Inspiron 15",
    category: "Tecnología",
    subcategory: "Computadoras",
    precioProducto: 3000,
    precioPublico: 3500,
    price: 3500,
    stock: 5,
    stockMin: 2,
    active: true,
  },
  {
    id: "2",
    sku: "TECH-002",
    name: "iPhone 15 Pro Max",
    category: "Tecnología",
    subcategory: "Celulares",
    precioProducto: 7500,
    precioPublico: 8500,
    price: 8500,
    stock: 8,
    stockMin: 3,
    active: true,
  },
  {
    id: "3",
    sku: "ROPA-001",
    name: "Camisa Polo Hombre",
    category: "Venta de Ropa",
    subcategory: "Hombre",
    precioProducto: 100,
    precioPublico: 150,
    price: 150,
    stock: 25,
    stockMin: 10,
    active: true,
  },
  {
    id: "4",
    sku: "ROPA-002",
    name: "Vestido Casual Mujer",
    category: "Venta de Ropa",
    subcategory: "Mujer",
    precioProducto: 200,
    precioPublico: 280,
    price: 280,
    stock: 15,
    stockMin: 8,
    active: true,
  },
  {
    id: "5",
    sku: "BOD-001",
    name: "Arroz Blanco 25lb",
    category: "Bodega",
    subcategory: "Alimentos",
    precioProducto: 50,
    precioPublico: 65,
    price: 65,
    stock: 40,
    stockMin: 15,
    active: true,
  },
  {
    id: "6",
    sku: "BOD-002",
    name: "Aceite de Cocina 1L",
    category: "Bodega",
    subcategory: "Alimentos",
    precioProducto: 28,
    precioPublico: 35,
    price: 35,
    stock: 50,
    stockMin: 20,
    active: true,
  },
  {
    id: "7",
    sku: "COM-001",
    name: "Cuaderno Universitario",
    category: "Comercio",
    subcategory: "Papelería",
    precioProducto: 18,
    precioPublico: 25,
    price: 25,
    stock: 50,
    stockMin: 20,
    active: true,
  },
  {
    id: "8",
    sku: "COM-002",
    name: "Bolígrafos Caja x12",
    category: "Comercio",
    subcategory: "Papelería",
    precioProducto: 10,
    precioPublico: 15,
    price: 15,
    stock: 100,
    stockMin: 30,
    active: true,
  },
  {
    id: "9",
    sku: "TECH-003",
    name: "Auriculares Bluetooth",
    category: "Tecnología",
    subcategory: "Accesorios",
    precioProducto: 85,
    precioPublico: 120,
    price: 120,
    stock: 20,
    stockMin: 8,
    active: true,
  },
  {
    id: "10",
    sku: "ROPA-003",
    name: "Zapatillas Deportivas",
    category: "Venta de Ropa",
    subcategory: "Accesorios",
    precioProducto: 350,
    precioPublico: 450,
    price: 450,
    stock: 12,
    stockMin: 5,
    active: true,
  },
  {
    id: "11",
    sku: "BOD-003",
    name: "Detergente en Polvo 2kg",
    category: "Bodega",
    subcategory: "Productos de Limpieza",
    precioProducto: 20,
    precioPublico: 28,
    price: 28,
    stock: 30,
    stockMin: 12,
    active: true,
  },
  {
    id: "12",
    sku: "COM-003",
    name: "Calculadora Científica",
    category: "Comercio",
    subcategory: "Artículos de Oficina",
    precioProducto: 60,
    precioPublico: 85,
    price: 85,
    stock: 15,
    stockMin: 6,
    active: true,
  },
];

export const mockCategories = [
  "Tecnología",
  "Venta de Ropa", 
  "Bodega",
  "Comercio",
];
export const mockUnits = ["pza", "m", "kg", "lt"];

export const mockQuotes: Quote[] = [
  {
    id: "Q001",
    customerName: "TechStore Guatemala",
    validDays: 15,
    date: "2024-10-15",
    status: "open",
    total: 3650,
    items: [
      {
        productId: "1",
        productName: "Laptop Dell Inspiron 15",
        quantity: 1,
        price: 3500,
        discount: 0,
        total: 3500,
      },
      {
        productId: "3",
        productName: "Camisa Polo Hombre",
        quantity: 1,
        price: 150,
        discount: 0,
        total: 150,
      },
    ],
  },
  {
    id: "Q002",
    customerName: "Boutique Elegancia",
    validDays: 10,
    date: "2024-10-18",
    status: "open",
    total: 730,
    items: [
      {
        productId: "4",
        productName: "Vestido Casual Mujer",
        quantity: 2,
        price: 280,
        discount: 0,
        total: 560,
      },
      {
        productId: "10",
        productName: "Zapatillas Deportivas",
        quantity: 1,
        price: 450,
        discount: 280,
        total: 170,
      },
    ],
  },
  {
    id: "Q003",
    customerName: "Supermercado Central",
    validDays: 20,
    date: "2024-10-12",
    status: "won",
    total: 128,
    items: [
      {
        productId: "5",
        productName: "Arroz Blanco 25lb",
        quantity: 1,
        price: 65,
        discount: 0,
        total: 65,
      },
      {
        productId: "6",
        productName: "Aceite de Cocina 1L",
        quantity: 1,
        price: 35,
        discount: 0,
        total: 35,
      },
      {
        productId: "11",
        productName: "Detergente en Polvo 2kg",
        quantity: 1,
        price: 28,
        discount: 0,
        total: 28,
      },
    ],
  },
  {
    id: "Q004",
    customerName: "Librería Estudiantil",
    validDays: 7,
    date: "2024-10-20",
    status: "open",
    total: 125,
    items: [
      {
        productId: "7",
        productName: "Cuaderno Universitario",
        quantity: 4,
        price: 25,
        discount: 0,
        total: 100,
      },
      {
        productId: "8",
        productName: "Bolígrafos Caja x12",
        quantity: 1,
        price: 15,
        discount: 0,
        total: 15,
      },
      {
        productId: "12",
        productName: "Calculadora Científica",
        quantity: 1,
        price: 85,
        discount: 75,
        total: 10,
      },
    ],
  },
  {
    id: "Q005",
    customerName: "Electrónicos Modernos",
    validDays: 30,
    date: "2024-10-10",
    status: "lost",
    total: 8620,
    items: [
      {
        productId: "2",
        productName: "iPhone 15 Pro Max",
        quantity: 1,
        price: 8500,
        discount: 0,
        total: 8500,
      },
      {
        productId: "9",
        productName: "Auriculares Bluetooth",
        quantity: 1,
        price: 120,
        discount: 0,
        total: 120,
      },
    ],
  },
];

export const mockSales: Sale[] = [
  {
    id: "S001",
    date: "2024-10-21",
    total: 67,
    status: "completed",
    employeeId: "emp1",
    customerName: "Juan Pérez",
    items: [
      {
        productId: "1",
        productName: "Martillo 16oz",
        quantity: 1,
        price: 35,
        discount: 0,
        total: 35,
      },
      {
        productId: "2",
        productName: "Destornillador Phillips",
        quantity: 2,
        price: 12,
        discount: 0,
        total: 24,
      },
      {
        productId: "6",
        productName: "Cinta Aislante",
        quantity: 1,
        price: 5,
        discount: 0,
        total: 5,
      },
    ],
  },
  {
    id: "S002",
    date: "2024-10-21",
    total: 150,
    status: "completed",
    employeeId: "emp1",
    customerName: "María García",
    items: [
      {
        productId: "8",
        productName: "Pintura Blanca 1 galón",
        quantity: 3,
        price: 50,
        discount: 0,
        total: 150,
      },
    ],
  },
  {
    id: "S003",
    date: "2024-10-20",
    total: 96,
    status: "completed",
    employeeId: "emp1",
    items: [
      {
        productId: "4",
        productName: "Tubo PVC 4 pulgadas",
        quantity: 4,
        price: 18,
        discount: 0,
        total: 72,
      },
      {
        productId: "13",
        productName: "Pegamento PVC",
        quantity: 2,
        price: 9,
        discount: 0,
        total: 18,
      },
    ],
  },
  {
    id: "S004",
    date: "2024-10-20",
    total: 44,
    status: "completed",
    employeeId: "emp2",
    items: [
      {
        productId: "5",
        productName: "Foco LED 12W",
        quantity: 2,
        price: 22,
        discount: 0,
        total: 44,
      },
    ],
  },
  {
    id: "S005",
    date: "2024-10-19",
    total: 180,
    status: "completed",
    employeeId: "emp1",
    customerNit: "12345678",
    items: [
      {
        productId: "7",
        productName: "Taladro Eléctrico",
        quantity: 1,
        price: 180,
        discount: 0,
        total: 180,
      },
    ],
  },
  {
    id: "S006",
    date: "2024-10-19",
    total: 36,
    status: "completed",
    employeeId: "emp2",
    items: [
      {
        productId: "9",
        productName: "Clavos 2 pulgadas",
        quantity: 3,
        price: 12,
        discount: 0,
        total: 36,
      },
    ],
  },
  {
    id: "S007",
    date: "2024-10-18",
    total: 28,
    status: "completed",
    employeeId: "emp1",
    items: [
      {
        productId: "10",
        productName: 'Llave Inglesa 10"',
        quantity: 1,
        price: 28,
        discount: 0,
        total: 28,
      },
    ],
  },
  {
    id: "S008",
    date: "2024-10-18",
    total: 60,
    status: "completed",
    employeeId: "emp2",
    items: [
      {
        productId: "11",
        productName: "Cable Eléctrico 12AWG",
        quantity: 20,
        price: 3,
        discount: 0,
        total: 60,
      },
    ],
  },
  {
    id: "S009",
    date: "2024-10-17",
    total: 64,
    status: "completed",
    employeeId: "emp1",
    items: [
      {
        productId: "12",
        productName: "Sierra de Mano",
        quantity: 2,
        price: 32,
        discount: 0,
        total: 64,
      },
    ],
  },
  {
    id: "S010",
    date: "2024-10-17",
    total: 18,
    status: "completed",
    employeeId: "emp2",
    customerName: "Pedro López",
    items: [
      {
        productId: "17",
        productName: "Candado 40mm",
        quantity: 1,
        price: 18,
        discount: 0,
        total: 18,
      },
    ],
  },
];

export const mockKardex: KardexEntry[] = [
  {
    id: "K001",
    productId: "1",
    type: "purchase",
    quantity: 20,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K002",
    productId: "1",
    type: "sale",
    quantity: -1,
    date: "2024-10-21",
    note: "Venta S001",
  },
  {
    id: "K003",
    productId: "2",
    type: "purchase",
    quantity: 30,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K004",
    productId: "2",
    type: "sale",
    quantity: -2,
    date: "2024-10-21",
    note: "Venta S001",
  },
  {
    id: "K005",
    productId: "3",
    type: "purchase",
    quantity: 15,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K006",
    productId: "4",
    type: "purchase",
    quantity: 40,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K007",
    productId: "4",
    type: "sale",
    quantity: -4,
    date: "2024-10-20",
    note: "Venta S003",
  },
  {
    id: "K008",
    productId: "5",
    type: "purchase",
    quantity: 50,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K009",
    productId: "5",
    type: "sale",
    quantity: -2,
    date: "2024-10-20",
    note: "Venta S004",
  },
  {
    id: "K010",
    productId: "6",
    type: "purchase",
    quantity: 60,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K011",
    productId: "6",
    type: "sale",
    quantity: -1,
    date: "2024-10-21",
    note: "Venta S001",
  },
  {
    id: "K012",
    productId: "7",
    type: "purchase",
    quantity: 8,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K013",
    productId: "7",
    type: "sale",
    quantity: -1,
    date: "2024-10-19",
    note: "Venta S005",
  },
  {
    id: "K014",
    productId: "8",
    type: "purchase",
    quantity: 20,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K015",
    productId: "8",
    type: "sale",
    quantity: -3,
    date: "2024-10-21",
    note: "Venta S002",
  },
  {
    id: "K016",
    productId: "9",
    type: "purchase",
    quantity: 25,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K017",
    productId: "9",
    type: "sale",
    quantity: -3,
    date: "2024-10-19",
    note: "Venta S006",
  },
  {
    id: "K018",
    productId: "10",
    type: "purchase",
    quantity: 15,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K019",
    productId: "10",
    type: "sale",
    quantity: -1,
    date: "2024-10-18",
    note: "Venta S007",
  },
  {
    id: "K020",
    productId: "11",
    type: "purchase",
    quantity: 150,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K021",
    productId: "11",
    type: "sale",
    quantity: -20,
    date: "2024-10-18",
    note: "Venta S008",
  },
  {
    id: "K022",
    productId: "12",
    type: "purchase",
    quantity: 12,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K023",
    productId: "12",
    type: "sale",
    quantity: -2,
    date: "2024-10-17",
    note: "Venta S009",
  },
  {
    id: "K024",
    productId: "13",
    type: "purchase",
    quantity: 20,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K025",
    productId: "13",
    type: "sale",
    quantity: -2,
    date: "2024-10-20",
    note: "Venta S003",
  },
  {
    id: "K026",
    productId: "17",
    type: "purchase",
    quantity: 18,
    date: "2024-10-01",
    note: "Compra inicial",
  },
  {
    id: "K027",
    productId: "17",
    type: "sale",
    quantity: -1,
    date: "2024-10-17",
    note: "Venta S010",
  },
  {
    id: "K028",
    productId: "1",
    type: "adjustment",
    quantity: 1,
    date: "2024-10-15",
    note: "Ajuste por inventario",
  },
  {
    id: "K029",
    productId: "5",
    type: "adjustment",
    quantity: -5,
    date: "2024-10-12",
    note: "Productos dañados",
  },
  {
    id: "K030",
    productId: "3",
    type: "return",
    quantity: 2,
    date: "2024-10-16",
    note: "Devolución cliente",
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "F001",
    uuid: "123e4567-e89b-12d3-a456-426614174001",
    series: "FEL",
    number: "000001",
    date: "2024-10-21",
    total: 67,
    status: "certified",
    saleId: "S001",
  },
  {
    id: "F002",
    uuid: "123e4567-e89b-12d3-a456-426614174002",
    series: "FEL",
    number: "000002",
    date: "2024-10-21",
    total: 150,
    status: "certified",
    saleId: "S002",
  },
  {
    id: "F003",
    uuid: "123e4567-e89b-12d3-a456-426614174003",
    series: "FEL",
    number: "000003",
    date: "2024-10-20",
    total: 96,
    status: "certified",
    saleId: "S003",
  },
  {
    id: "F004",
    uuid: "123e4567-e89b-12d3-a456-426614174004",
    series: "FEL",
    number: "000004",
    date: "2024-10-20",
    total: 44,
    status: "certified",
    saleId: "S004",
  },
  {
    id: "F005",
    uuid: "123e4567-e89b-12d3-a456-426614174005",
    series: "FEL",
    number: "000005",
    date: "2024-10-19",
    total: 180,
    status: "voided",
    saleId: "S005",
  },
  {
    id: "F006",
    uuid: "123e4567-e89b-12d3-a456-426614174006",
    series: "FEL",
    number: "000006",
    date: "2024-10-19",
    total: 36,
    status: "certified",
    saleId: "S006",
  },
  {
    id: "F007",
    uuid: "123e4567-e89b-12d3-a456-426614174007",
    series: "FEL",
    number: "000007",
    date: "2024-10-18",
    total: 28,
    status: "error",
  },
  {
    id: "F008",
    uuid: "123e4567-e89b-12d3-a456-426614174008",
    series: "FEL",
    number: "000008",
    date: "2024-10-17",
    total: 18,
    status: "certified",
    saleId: "S010",
  },
];

export const mockUsers = [
  {
    id: "admin1",
    name: "Administrador",
    email: "admin@TECNOCELL by EMPRENDE360.com",
    role: "admin",
    active: true,
  },
  { id: "emp1", name: "Juan Pérez", email: "juan@TECNOCELL by EMPRENDE360.com", role: "employee", active: true },
  {
    id: "emp2",
    name: "María García",
    email: "maria@TECNOCELL by EMPRENDE360.com",
    role: "employee",
    active: true,
  },
  {
    id: "emp3",
    name: "Carlos López",
    email: "carlos@TECNOCELL by EMPRENDE360.com",
    role: "employee",
    active: false,
  },
];
